# Generated by Django 5.1 on 2024-08-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_armazem',
            name='old_nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_armazem',
            name='old_tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
